"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "../../../lib/supabase/client";
function monthBounds(v){const[y,m]=v.split("-").map(Number),s=new Date(y,m-1,1),e=new Date(y,m,1);return{start:s.toISOString(),end:e.toISOString()};}
export default function SettlementStatementPage(){
const[companyId,setCompanyId]=useState(""),[month,setMonth]=useState(""),[restaurant,setRestaurant]=useState(null),[company,setCompany]=useState(null),[records,setRecords]=useState([]),[loading,setLoading]=useState(true);
useEffect(()=>{const p=new URLSearchParams(location.search);setCompanyId(p.get("company")||"");setMonth(p.get("month")||"");},[]);
useEffect(()=>{if(!companyId||!month)return;(async()=>{const s=createClient();const{data:{user}}=await s.auth.getUser();if(!user){location.replace("/login");return;}const{data:m}=await s.from("restaurant_members").select("restaurant_id").eq("user_id",user.id).limit(1).maybeSingle();if(!m?.restaurant_id){location.replace("/onboarding");return;}const{start,end}=monthBounds(month);const[{data:r},{data:c},{data:meals}]=await Promise.all([s.from("restaurants").select("id,name,phone").eq("id",m.restaurant_id).single(),s.from("companies").select("id,restaurant_id,company_no,name,lunch_price,dinner_price,contact_name,contact_email,business_number,business_address,company_phone,contact_phone").eq("id",companyId).eq("restaurant_id",m.restaurant_id).single(),s.from("meal_records").select("id,company_id,meal_type,headcount,unit_price,occurred_at,cancelled_at").eq("restaurant_id",m.restaurant_id).eq("company_id",companyId).is("cancelled_at",null).gte("occurred_at",start).lt("occurred_at",end).order("occurred_at")]);setRestaurant(r||null);setCompany(c||null);setRecords(meals||[]);setLoading(false);})();},[companyId,month]);
const dailyRows=useMemo(()=>{if(!company)return[];const map=new Map();records.forEach(r=>{const date=new Date(r.occurred_at).toLocaleDateString("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"});if(!map.has(date))map.set(date,{date,lunch:0,dinner:0,amount:0});const x=map.get(date),n=Number(r.headcount||0),fallback=r.meal_type==="lunch"?Number(company.lunch_price||0):Number(company.dinner_price||0),unit=Number(r.unit_price||fallback);if(r.meal_type==="lunch")x.lunch+=n;else x.dinner+=n;x.amount+=n*unit;});return[...map.values()];},[records,company]);
const summary=useMemo(()=>{let lunch=0,dinner=0,lunchAmount=0,dinnerAmount=0;if(!company)return{lunch,dinner,lunchAmount,dinnerAmount,total:0,amount:0};records.forEach(r=>{const n=Number(r.headcount||0),fallback=r.meal_type==="lunch"?Number(company.lunch_price||0):Number(company.dinner_price||0),unit=Number(r.unit_price||fallback);if(r.meal_type==="lunch"){lunch+=n;lunchAmount+=n*unit}else{dinner+=n;dinnerAmount+=n*unit}});return{lunch,dinner,lunchAmount,dinnerAmount,total:lunch+dinner,amount:lunchAmount+dinnerAmount};},[records,company]);
if(loading)return <main className="center-shell"><div className="form-card"><p className="helper">정산서를 만들고 있습니다...</p></div></main>;if(!company||!restaurant)return <main className="center-shell"><div className="form-card"><p className="error">정산서 정보를 찾을 수 없습니다.</p><a className="btn secondary" href="/dashboard">홈으로 돌아가기</a></div></main>;
const monthText=`${month.slice(0,4)}년 ${Number(month.slice(5,7))}월`,subject=`${restaurant.name} ${monthText} 식대 정산서`,body=`${company.name} 담당자님, 안녕하세요.\n\n${monthText} 식대 정산내역을 보내드립니다.\n총 식수: ${summary.total}명\n청구금액: ${summary.amount.toLocaleString()}원\n\n감사합니다.\n${restaurant.name}`,mailHref=`mailto:${encodeURIComponent(company.contact_email||"")}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
return <main className="statement-shell"><div className="statement-toolbar no-print"><div><a className="btn secondary" href="/dashboard">홈으로</a><a className="btn secondary" href={`/settlement?month=${month}`}>정산 목록</a></div><div><a className="btn secondary" href={mailHref}>이메일 작성</a><button className="btn primary" onClick={()=>window.print()}>PDF 저장 · 인쇄</button></div></div><article className="statement-paper"><header className="statement-head"><div><span>한끼장부</span><h1>식대 정산서</h1><p>{monthText}</p></div><div className="statement-brand"><strong>{restaurant.name}</strong>{restaurant.phone&&<span>{restaurant.phone}</span>}</div></header><section className="statement-parties"><div><span>공급자</span><strong>{restaurant.name}</strong></div><div><span>청구처</span><strong>{company.name}</strong><small>업체번호 {company.company_no}</small>{company.business_number&&<small>사업자등록번호 {company.business_number}</small>}{company.business_address&&<small>{company.business_address}</small>}{company.company_phone&&<small>대표 연락처 {company.company_phone}</small>}{company.contact_name&&<small>담당 {company.contact_name}{company.contact_phone?` · ${company.contact_phone}`:""}</small>}{company.contact_email&&<small>{company.contact_email}</small>}</div></section><section className="statement-summary"><div><span>중식</span><strong>{summary.lunch.toLocaleString()}명</strong><small>{summary.lunchAmount.toLocaleString()}원</small></div><div><span>석식</span><strong>{summary.dinner.toLocaleString()}명</strong><small>{summary.dinnerAmount.toLocaleString()}원</small></div><div><span>총 식수</span><strong>{summary.total.toLocaleString()}명</strong></div><div className="amount"><span>청구금액</span><strong>{summary.amount.toLocaleString()}원</strong></div></section><section className="statement-detail"><h2>일자별 이용내역</h2><table><thead><tr><th>일자</th><th>중식</th><th>석식</th><th>금액</th></tr></thead><tbody>{dailyRows.length?dailyRows.map(r=><tr key={r.date}><td>{r.date}</td><td>{r.lunch}명</td><td>{r.dinner}명</td><td>{r.amount.toLocaleString()}원</td></tr>):<tr><td colSpan="4">이용내역이 없습니다.</td></tr>}</tbody><tfoot><tr><td>합계</td><td>{summary.lunch}명</td><td>{summary.dinner}명</td><td>{summary.amount.toLocaleString()}원</td></tr></tfoot></table></section><footer className="statement-footer"><p>본 정산서는 한끼장부에 기록된 취소되지 않은 식수 내역을 기준으로 작성되었습니다.</p><strong>{restaurant.name}</strong></footer></article></main>;
}
